### ISSUE TITLE
Bug error 404 : the server sends a 404 error and the page is working correctly

### ISSUE THREAD

**Issue by montuy337513** [XoopsModules25x/news#23]
A funny bug, with the News module. Maybe with other modules too.

On any page of the site (front / back), the server returns me a 404 error header.
The pages are displayed correctly. Some JS functionality is disrupted. Example: Activate / deactivate a module in the "Module manager". For the changes to show, I have to reload the page. Another example: the notification bubble that appears with a late page.

Here is the screenshot of my console
![image](https://user-images.githubusercontent.com/11269795/144274808-7fc9c1e0-5467-45d0-b9fb-784bd3b87466.png)

The fault is the /preloads/index.php file
If I delete it, I find my headers 200

I think the Core loads all the PHP files present in / preloads. Including the index.php which asks the server to send a 404 header.
The page is displayed correctly, if we did not work with an open console next to it. We can miss the problem.

**Recommendations:**
- delete the file /preloads/index.php
Where
- Modify the function of the Core which manages the / preloads. To exclude index.php files (provided that no dev has created a /preloads/index.php file with important functions)
And check in all modules that have a / preloads directory for the presence and content of the /preloads/index.php file

**Comment by zyspec** [comment]
Interesting problem.  The core XoopsPreload::setPreloads() method does check for index and discards it.  The issue must be somewhere else.  Can you tell us which version of XOOPS you're using?    On Wednesday, December 1, 2021, 11:09:33 AM CST, montuy337513 ***@***.***> wrote:  
 
 


A funny bug, with the News module. Maybe with other modules too.

On any page of the site (front / back), the server returns me a 404 error header.
The pages are displayed correctly. Some JS functionality is disrupted. Example: Activate / deactivate a module in the "Module manager". For the changes to show, I have to reload the page. Another example: the notification bubble that appears with a late page.

Here is the screenshot of my console


The fault is the /preloads/index.php file
If I delete it, I find my headers 200

I think the Core loads all the PHP files present in / preloads. Including the index.php which asks the server to send a 404 header.
The page is displayed correctly, if we did not work with an open console next to it. We can miss the problem.

Recommendations:
   
   - delete the file /preloads/index.php   
Where
   - Modify the function of the Core which manages the / preloads. To exclude index.php files (provided that no dev has created a /preloads/index.php file with important functions)   
And check in all modules that have a / preloads directory for the presence and content of the /preloads/index.php file

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by montuy337513** [comment]
The latest version for production : Xoops 2.5.10 Final.
I tested by removing 1 by 1 all index.php.
It is only /preloads/index.php that causes this error.

**Comment by mambax7** [comment]
Thanks! It was fixed in https://github.com/XoopsModules25x/news/commit/c7f65a2762b4ce279954c8a7350c20a21679dabb
